= jnc-downloader
A python script to download ebooks from your j-novel.club library.


== How to use
Just adjust the values in the config area denoted at the top of the jnc.py file and execute the script.

By default, it will only download already purchased books from your library.
Use `--update-books` to also download updated epubs.
Note that when running this for the first time and used versions <= 2.5.1 of this tool, it may re-download a large portion of your library.

It will also ask you if you want to follow series it does not know about yet and print avaliable volumes you don't own of series you follow.

The script optionally supports auto order of books and auto purchase of premium credits.
For details about this, refer to the output of `python3 jnc.py --help`

== Limitations
It only work if you have an account directly with J-Novel.club. If you log in using Google/Facebook, this script will not work.

== Security considerations
The script will store your JNC access token on disk. Your email/password *will not* be stored.
This means any program running as root or with your user will be, in principle, able to access those credentials and access your JNC account.
Whether or not you are comfortable with this is up to you.
